Added feature support symbols.
git-svn-id: https://aug.svn.sourceforge.net/svnroot/aug/trunk@403 a3a97f7c-8e16-0410-9893-1d5f7d0f8f6e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -875,10 +875,14 @@ F77
 FFLAGS
 ac_ct_F77
 LIBTOOL
+ENABLE_MULTICAST_TRUE
+ENABLE_MULTICAST_FALSE
 ENABLE_PYTHON_TRUE
 ENABLE_PYTHON_FALSE
 ENABLE_RUBY_TRUE
 ENABLE_RUBY_FALSE
+ENABLE_SSL_TRUE
+ENABLE_SSL_FALSE
 ENABLE_THREADS_TRUE
 ENABLE_THREADS_FALSE
 ALLOCA
@@ -1488,8 +1492,10 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --enable-multicast      enable multicast support [default=yes]
   --enable-python         enable python support [default=yes]
   --enable-ruby           enable ruby support [default=no]
+  --enable-ssl            enable ssl support [default=yes]
   --enable-threads        enable threads support [default=yes]
 
 Optional Packages:
@@ -5156,7 +5162,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5159 "configure"' > conftest.$ac_ext
+  echo '#line 5165 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7482,11 +7488,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7485: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7491: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7489: \$? = $ac_status" >&5
+   echo "$as_me:7495: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7772,11 +7778,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7775: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7781: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7779: \$? = $ac_status" >&5
+   echo "$as_me:7785: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7876,11 +7882,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7879: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7885: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7883: \$? = $ac_status" >&5
+   echo "$as_me:7889: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10186,7 +10192,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10189 "configure"
+#line 10195 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10286,7 +10292,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10289 "configure"
+#line 10295 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12701,11 +12707,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12704: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12710: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12708: \$? = $ac_status" >&5
+   echo "$as_me:12714: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12805,11 +12811,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12808: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12814: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12812: \$? = $ac_status" >&5
+   echo "$as_me:12818: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14384,11 +14390,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14387: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14393: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14391: \$? = $ac_status" >&5
+   echo "$as_me:14397: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14488,11 +14494,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14491: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14497: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14495: \$? = $ac_status" >&5
+   echo "$as_me:14501: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16688,11 +16694,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16691: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16697: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16695: \$? = $ac_status" >&5
+   echo "$as_me:16701: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16978,11 +16984,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16981: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16987: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16985: \$? = $ac_status" >&5
+   echo "$as_me:16991: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17082,11 +17088,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17085: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17091: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17089: \$? = $ac_status" >&5
+   echo "$as_me:17095: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19747,6 +19753,39 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 
 
+# Check whether --enable-multicast was given.
+if test "${enable_multicast+set}" = set; then
+  enableval=$enable_multicast;
+    case "${enableval}" in
+        yes) enable_multicast=yes;;
+        no)  enable_multicast=no;;
+        *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-multicast" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-multicast" >&2;}
+   { (exit 1); exit 1; }; };;
+    esac
+
+else
+  enable_multicast=yes
+fi
+
+
+
+if test x$enable_multicast = xyes; then
+  ENABLE_MULTICAST_TRUE=
+  ENABLE_MULTICAST_FALSE='#'
+else
+  ENABLE_MULTICAST_TRUE='#'
+  ENABLE_MULTICAST_FALSE=
+fi
+
+if test x$enable_multicast = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_MULTICAST 1
+_ACEOF
+
+fi
+
 # Check whether --enable-python was given.
 if test "${enable_python+set}" = set; then
   enableval=$enable_python;
@@ -19772,6 +19811,13 @@ else
   ENABLE_PYTHON_FALSE=
 fi
 
+if test x$enable_python = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_PYTHON 1
+_ACEOF
+
+fi
 
 # Check whether --enable-ruby was given.
 if test "${enable_ruby+set}" = set; then
@@ -19798,6 +19844,46 @@ else
   ENABLE_RUBY_FALSE=
 fi
 
+if test x$enable_ruby = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_RUBY 1
+_ACEOF
+
+fi
+
+# Check whether --enable-ssl was given.
+if test "${enable_ssl+set}" = set; then
+  enableval=$enable_ssl;
+    case "${enableval}" in
+        yes) enable_ssl=yes;;
+        no)  enable_ssl=no;;
+        *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-ssl" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-ssl" >&2;}
+   { (exit 1); exit 1; }; };;
+    esac
+
+else
+  enable_ssl=yes
+fi
+
+
+
+if test x$enable_ssl = xyes; then
+  ENABLE_SSL_TRUE=
+  ENABLE_SSL_FALSE='#'
+else
+  ENABLE_SSL_TRUE='#'
+  ENABLE_SSL_FALSE=
+fi
+
+if test x$enable_ssl = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_SSL 1
+_ACEOF
+
+fi
 
 # Check whether --enable-threads was given.
 if test "${enable_threads+set}" = set; then
@@ -19824,12 +19910,19 @@ else
   ENABLE_THREADS_FALSE=
 fi
 
+if test x$enable_threads = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_THREADS 1
+_ACEOF
+
+fi
 
 # Checks for libraries.
 
 LDFLAGS="-lm $LDFLAGS"
 
-if test x$enable_threads != xno; then
+if test x$enable_threads = xyes; then
    CFLAGS="-D_MT -D_REENTRANT $CFLAGS"
    CXXFLAGS="-D_MT -D_REENTRANT $CXXFLAGS"
 fi
@@ -19842,7 +19935,8 @@ case $host in
     # cp ssleay32.a libssleay32.a
     # cp lib*.a /lib/mingw/
 
-    { echo "$as_me:$LINENO: checking for library containing SSL_library_init" >&5
+    if test x$enable_ssl = xyes; then
+        { echo "$as_me:$LINENO: checking for library containing SSL_library_init" >&5
 echo $ECHO_N "checking for library containing SSL_library_init... $ECHO_C" >&6; }
 if test "${ac_cv_search_SSL_library_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -19925,7 +20019,7 @@ if test "$ac_res" != no; then
 
 fi
 
-    { echo "$as_me:$LINENO: checking for library containing BIO_new" >&5
+        { echo "$as_me:$LINENO: checking for library containing BIO_new" >&5
 echo $ECHO_N "checking for library containing BIO_new... $ECHO_C" >&6; }
 if test "${ac_cv_search_BIO_new+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20008,20 +20102,27 @@ if test "$ac_res" != no; then
 
 fi
 
+    fi
 
-    CFLAGS="$CFLAGS -DWINVER=0x0501 -DFD_SETSIZE=256"
-    CXXFLAGS="$CXXFLAGS -DWINVER=0x0501 -DFD_SETSIZE=256"
-    LDFLAGS="-lws2_32 -liphlpapi $LDFLAGS"
-    LIBS="-Wl,-lws2_32 -Wl,-liphlpapi $LIBS"
+    CFLAGS="-DWINVER=0x0501 -DFD_SETSIZE=256 $CFLAGS"
+    CXXFLAGS="-DWINVER=0x0501 -DFD_SETSIZE=256 $CXXFLAGS"
+    LDFLAGS="-lws2_32 $LDFLAGS"
+    LIBS="-Wl,-lws2_32 $LIBS"
 
-    if test x$enable_threads != xno; then
+    if test x$enable_multicast = xyes; then
+        LDFLAGS="-liphlpapi $LDFLAGS"
+        LIBS="-Wl,-liphlpapi $LIBS"
+    fi
+
+    if test x$enable_threads = xyes; then
         CFLAGS="-mthreads $CFLAGS"
         CXXFLAGS="-mthreads $CXXFLAGS"
         LDFLAGS="-mthreads $LDFLAGS"
     fi
     ;;
 *)
-    { echo "$as_me:$LINENO: checking for library containing SSL_library_init" >&5
+    if test x$enable_ssl = xyes; then
+        { echo "$as_me:$LINENO: checking for library containing SSL_library_init" >&5
 echo $ECHO_N "checking for library containing SSL_library_init... $ECHO_C" >&6; }
 if test "${ac_cv_search_SSL_library_init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20104,7 +20205,7 @@ if test "$ac_res" != no; then
 
 fi
 
-    { echo "$as_me:$LINENO: checking for library containing BIO_new" >&5
+        { echo "$as_me:$LINENO: checking for library containing BIO_new" >&5
 echo $ECHO_N "checking for library containing BIO_new... $ECHO_C" >&6; }
 if test "${ac_cv_search_BIO_new+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -20187,6 +20288,7 @@ if test "$ac_res" != no; then
 
 fi
 
+    fi
 
     { echo "$as_me:$LINENO: checking for library containing gethostbyname" >&5
 echo $ECHO_N "checking for library containing gethostbyname... $ECHO_C" >&6; }
@@ -20521,7 +20623,7 @@ if test "$ac_res" != no; then
 fi
 
 
-    if test x$enable_threads != xno; then
+    if test x$enable_threads = xyes; then
         { echo "$as_me:$LINENO: checking for library containing pthread_create" >&5
 echo $ECHO_N "checking for library containing pthread_create... $ECHO_C" >&6; }
 if test "${ac_cv_search_pthread_create+set}" = set; then
@@ -21892,6 +21994,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${ENABLE_MULTICAST_TRUE}" && test -z "${ENABLE_MULTICAST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_MULTICAST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_MULTICAST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${ENABLE_PYTHON_TRUE}" && test -z "${ENABLE_PYTHON_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_PYTHON\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -21903,6 +22012,13 @@ if test -z "${ENABLE_RUBY_TRUE}" && test -z "${ENABLE_RUBY_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_RUBY\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"ENABLE_RUBY\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_SSL_TRUE}" && test -z "${ENABLE_SSL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_SSL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_SSL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -22634,10 +22750,14 @@ F77!$F77$ac_delim
 FFLAGS!$FFLAGS$ac_delim
 ac_ct_F77!$ac_ct_F77$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
+ENABLE_MULTICAST_TRUE!$ENABLE_MULTICAST_TRUE$ac_delim
+ENABLE_MULTICAST_FALSE!$ENABLE_MULTICAST_FALSE$ac_delim
 ENABLE_PYTHON_TRUE!$ENABLE_PYTHON_TRUE$ac_delim
 ENABLE_PYTHON_FALSE!$ENABLE_PYTHON_FALSE$ac_delim
 ENABLE_RUBY_TRUE!$ENABLE_RUBY_TRUE$ac_delim
 ENABLE_RUBY_FALSE!$ENABLE_RUBY_FALSE$ac_delim
+ENABLE_SSL_TRUE!$ENABLE_SSL_TRUE$ac_delim
+ENABLE_SSL_FALSE!$ENABLE_SSL_FALSE$ac_delim
 ENABLE_THREADS_TRUE!$ENABLE_THREADS_TRUE$ac_delim
 ENABLE_THREADS_FALSE!$ENABLE_THREADS_FALSE$ac_delim
 ALLOCA!$ALLOCA$ac_delim
@@ -22645,7 +22765,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 19; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
