Addition of aug_gmtoff() function.
git-svn-id: https://aug.svn.sourceforge.net/svnroot/aug/trunk@432 a3a97f7c-8e16-0410-9893-1d5f7d0f8f6e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19923,8 +19923,8 @@ fi
 LDFLAGS="-lm $LDFLAGS"
 
 if test x$enable_threads = xyes; then
-   CFLAGS="-D_MT -D_REENTRANT $CFLAGS"
-   CXXFLAGS="-D_MT -D_REENTRANT $CXXFLAGS"
+   CFLAGS="-D_MT -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS $CFLAGS"
+   CXXFLAGS="-D_MT -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS $CXXFLAGS"
 fi
 
 case $host in
@@ -21763,6 +21763,66 @@ _ACEOF
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+{ echo "$as_me:$LINENO: checking for gmtoff in struct tm" >&5
+echo $ECHO_N "checking for gmtoff in struct tm... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <time.h>
+
+int
+main ()
+{
+
+    struct tm x;
+    x.tm_gmtoff;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+
+	{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TM_GMTOFF 1
+_ACEOF
+
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
 
 fi
 
