Improved support for threads in configure.in.
git-svn-id: https://aug.svn.sourceforge.net/svnroot/aug/trunk@158 a3a97f7c-8e16-0410-9893-1d5f7d0f8f6e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20329,6 +20329,11 @@ fi
 
 LDFLAGS="-lm $LDFLAGS"
 
+if test "$threads" != "no"; then
+   CFLAGS="-D_MT -D_REENTRANT $CFLAGS"
+   CXXFLAGS="-D_MT -D_REENTRANT $CXXFLAGS"
+fi
+
 case $host in
 *-*-cygwin* | *-*-mingw*)
 
@@ -20338,15 +20343,9 @@ case $host in
     LIBS="-Wl,-lws2_32 -Wl,-liphlpapi $LIBS"
 
     if test "$threads" != "no"; then
-        CFLAGS="-mthreads -D_MT $CFLAGS"
-        CXXFLAGS="-mthreads -D_MT $CXXFLAGS"
+        CFLAGS="-mthreads $CFLAGS"
+        CXXFLAGS="-mthreads $CXXFLAGS"
         LDFLAGS="-mthreads $LDFLAGS"
-    fi
-    ;;
-*-apple-darwin*)
-    if test "$threads" != "no"; then
-        CFLAGS="-D_MT $CFLAGS"
-        CXXFLAGS="-D_MT $CXXFLAGS"
     fi
     ;;
 *)
@@ -20675,7 +20674,7 @@ return dlopen ();
   return 0;
 }
 _ACEOF
-for ac_lib in '' dl; do
+for ac_lib in '' dl dlcompat; do
   if test -z "$ac_lib"; then
     ac_res="none required"
   else
@@ -20748,9 +20747,105 @@ fi
 
 
     if test "$threads" != "no"; then
-        CFLAGS="-pthread -D_MT $CFLAGS"
-        CXXFLAGS="-pthread -D_MT $CXXFLAGS"
-        LDFLAGS="-pthread $LDFLAGS"
+        { echo "$as_me:$LINENO: checking for library containing pthread_create" >&5
+echo $ECHO_N "checking for library containing pthread_create... $ECHO_C" >&6; }
+if test "${ac_cv_search_pthread_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char pthread_create ();
+int
+main ()
+{
+return pthread_create ();
+  ;
+  return 0;
+}
+_ACEOF
+for ac_lib in '' pthread; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_pthread_create=$ac_res
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext
+  if test "${ac_cv_search_pthread_create+set}" = set; then
+  break
+fi
+done
+if test "${ac_cv_search_pthread_create+set}" = set; then
+  :
+else
+  ac_cv_search_pthread_create=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_pthread_create" >&5
+echo "${ECHO_T}$ac_cv_search_pthread_create" >&6; }
+ac_res=$ac_cv_search_pthread_create
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
+fi
+
     fi
     ;;
 esac
